# Generated by Django 3.1.13 on 2021-11-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20211105_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Organizational_pin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Pin'),
        ),
    ]
