# Generated by Django 3.2.9 on 2021-11-04 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20211104_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('last_name',)},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Organization_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Organization_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Organization_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Organization_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization State'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Organization_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Organization_zip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization Zip'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Photo'),
        ),
    ]
