# Generated by Django 3.1.13 on 2021-11-16 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customuser', '0003_customuser_organizational_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
