# Generated by Django 3.1.13 on 2021-11-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Group',
        ),
    ]
