# Generated by Django 3.1.13 on 2021-11-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_remove_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Organizatoin_user_type',
            field=models.CharField(choices=[('General', 'GENERAL'), ('Information Technology', 'IT'), ('Research and Devleopment', 'R&D'), ('Security', 'SECURITY'), ('Marketing', 'MARKETING'), ('Finance', 'FINANCE'), ('Human Resources', 'HR')], default='general', max_length=24, verbose_name='Organization User Type'),
        ),
    ]
