# Generated by Django 3.1.13 on 2021-11-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_customuser_organizatoin_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Organizatoin_user_type',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('IT', 'Information Technology'), ('R&D', 'Research and Devleopment'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing'), ('FINANCE', 'Finance'), ('HR', 'Human Resources')], default='GENERAL', max_length=50, null=True, verbose_name='Organization User Type'),
        ),
    ]
